
import "./base.js";
import "./cljs-runtime/shadow.module.storage.prepend.js";
SHADOW_ENV.setLoaded("shadow.module.storage.prepend.js");
import "./cljs-runtime/nia.config.storage.js";
SHADOW_ENV.setLoaded("nia.config.storage.js");
import "./cljs-runtime/goog.disposable.idisposable.js";
SHADOW_ENV.setLoaded("goog.disposable.idisposable.js");
import "./cljs-runtime/goog.disposable.dispose.js";
SHADOW_ENV.setLoaded("goog.disposable.dispose.js");
import "./cljs-runtime/goog.disposable.disposeall.js";
SHADOW_ENV.setLoaded("goog.disposable.disposeall.js");
import "./cljs-runtime/goog.disposable.disposable.js";
SHADOW_ENV.setLoaded("goog.disposable.disposable.js");
import "./cljs-runtime/goog.events.eventid.js";
SHADOW_ENV.setLoaded("goog.events.eventid.js");
import "./cljs-runtime/goog.events.event.js";
SHADOW_ENV.setLoaded("goog.events.event.js");
import "./cljs-runtime/goog.events.browserfeature.js";
SHADOW_ENV.setLoaded("goog.events.browserfeature.js");
import "./cljs-runtime/goog.events.eventtypehelpers.js";
SHADOW_ENV.setLoaded("goog.events.eventtypehelpers.js");
import "./cljs-runtime/goog.events.eventtype.js";
SHADOW_ENV.setLoaded("goog.events.eventtype.js");
import "./cljs-runtime/goog.events.browserevent.js";
SHADOW_ENV.setLoaded("goog.events.browserevent.js");
import "./cljs-runtime/goog.events.listenable.js";
SHADOW_ENV.setLoaded("goog.events.listenable.js");
import "./cljs-runtime/goog.events.listenablekey.js";
SHADOW_ENV.setLoaded("goog.events.listenablekey.js");
import "./cljs-runtime/goog.events.listener.js";
SHADOW_ENV.setLoaded("goog.events.listener.js");
import "./cljs-runtime/goog.events.listenermap.js";
SHADOW_ENV.setLoaded("goog.events.listenermap.js");
import "./cljs-runtime/goog.events.events.js";
SHADOW_ENV.setLoaded("goog.events.events.js");
import "./cljs-runtime/shadow.esm.esm_import$react.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$react.js");
import "./cljs-runtime/reagent.debug.js";
SHADOW_ENV.setLoaded("reagent.debug.js");
import "./cljs-runtime/reagent.impl.util.js";
SHADOW_ENV.setLoaded("reagent.impl.util.js");
import "./cljs-runtime/reagent.impl.batching.js";
SHADOW_ENV.setLoaded("reagent.impl.batching.js");
import "./cljs-runtime/reagent.impl.protocols.js";
SHADOW_ENV.setLoaded("reagent.impl.protocols.js");
import "./cljs-runtime/reagent.ratom.js";
SHADOW_ENV.setLoaded("reagent.ratom.js");
import "./cljs-runtime/reagent.impl.component.js";
SHADOW_ENV.setLoaded("reagent.impl.component.js");
import "./cljs-runtime/reagent.impl.input.js";
SHADOW_ENV.setLoaded("reagent.impl.input.js");
import "./cljs-runtime/reagent.impl.template.js";
SHADOW_ENV.setLoaded("reagent.impl.template.js");
import "./cljs-runtime/reagent.core.js";
SHADOW_ENV.setLoaded("reagent.core.js");
import "./cljs-runtime/re_frame.interop.js";
SHADOW_ENV.setLoaded("re_frame.interop.js");
import "./cljs-runtime/re_frame.db.js";
SHADOW_ENV.setLoaded("re_frame.db.js");
import "./cljs-runtime/re_frame.loggers.js";
SHADOW_ENV.setLoaded("re_frame.loggers.js");
import "./cljs-runtime/re_frame.utils.js";
SHADOW_ENV.setLoaded("re_frame.utils.js");
import "./cljs-runtime/re_frame.settings.js";
SHADOW_ENV.setLoaded("re_frame.settings.js");
import "./cljs-runtime/re_frame.registrar.js";
SHADOW_ENV.setLoaded("re_frame.registrar.js");
import "./cljs-runtime/re_frame.trace.js";
SHADOW_ENV.setLoaded("re_frame.trace.js");
import "./cljs-runtime/re_frame.interceptor.js";
SHADOW_ENV.setLoaded("re_frame.interceptor.js");
import "./cljs-runtime/re_frame.events.js";
SHADOW_ENV.setLoaded("re_frame.events.js");
import "./cljs-runtime/re_frame.subs.js";
SHADOW_ENV.setLoaded("re_frame.subs.js");
import "./cljs-runtime/re_frame.register.alpha.js";
SHADOW_ENV.setLoaded("re_frame.register.alpha.js");
import "./cljs-runtime/re_frame.query.alpha.js";
SHADOW_ENV.setLoaded("re_frame.query.alpha.js");
import "./cljs-runtime/re_frame.subs.alpha.js";
SHADOW_ENV.setLoaded("re_frame.subs.alpha.js");
import "./cljs-runtime/re_frame.router.js";
SHADOW_ENV.setLoaded("re_frame.router.js");
import "./cljs-runtime/re_frame.fx.js";
SHADOW_ENV.setLoaded("re_frame.fx.js");
import "./cljs-runtime/re_frame.cofx.js";
SHADOW_ENV.setLoaded("re_frame.cofx.js");
import "./cljs-runtime/re_frame.std_interceptors.js";
SHADOW_ENV.setLoaded("re_frame.std_interceptors.js");
import "./cljs-runtime/re_frame.flow.alpha.js";
SHADOW_ENV.setLoaded("re_frame.flow.alpha.js");
import "./cljs-runtime/re_frame.alpha.js";
SHADOW_ENV.setLoaded("re_frame.alpha.js");
import "./cljs-runtime/re_frame.core.js";
SHADOW_ENV.setLoaded("re_frame.core.js");
import "./cljs-runtime/shadow.cljs.modern.js";
SHADOW_ENV.setLoaded("shadow.cljs.modern.js");
import "./cljs-runtime/shadow.esm.esm_import$$azure$storage_blob.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$azure$storage_blob.js");
import "./cljs-runtime/nia.events.storage.js";
SHADOW_ENV.setLoaded("nia.events.storage.js");
import "./cljs-runtime/shadow.module.storage.append.js";
SHADOW_ENV.setLoaded("shadow.module.storage.append.js");


shadow.cljs.devtools.client.env.module_loaded("storage");