(ns nia.views.cantos.four.parens-four
  (:require [clojure.string :as str]
            [re-com.core :refer [hyperlink p v-box]]
            [reitit.frontend.easy :as rfe]))

(defn parens-four []
  [v-box
   :margin "10px 0px"
   :children
   [[p "a star that appears to us today"]
    [p "Like a fire whose twinkling light has penetrated through,"]
    [p "Will, when water has covered all the bare earth"]
    [p "Except for peaks as yet unclimbed,"]
    [p "Already be one of the extinct worlds..."]
    [p "All fires go out, within us as in nature:-"]
    [p "On the envelopes which one can only obtain with a counter-signature"]
    [p "The sender has extinguished each seal with a puff;"]
    [p "- Old age puts out certain fires: tireless, the young cock"]
    [p "Takes all-comers, pullets, hens at point-of-lay, old chickens..."]
    [p "The mature cockerel uses his discretion; - inside cowards"]
    [p "Is a flame which never fails to burn when danger is present"]
    [p [:b.text-primary "((((("]
     "A burning fire this, but an illusion; no-one would ever run from it"]
    [p "Or see its embers, and the hare"]
    [p "Would never notice it making the frogs run faster" [:b.text-primary ")))))"] ";"]
    [:a {:name "fn1ret"} "fever"]
    [p "Makes a fire which goes out, either when the patient dies"]
    [p "Or when, the fever at its peak and looking dangerous,"]
    [p "One's shining eyes and "
     [:a {:href "#fn1"} "deep blisters"] ","] 
    [p "- Fever makes even adults grow, it's a well-known fact -"]
    [p "Gradually transform into blooming convalesence,"]
    [p "And ravenous hunger drives one to eat like a hundred men,"]
    [p "With a tongue which is once more good and red;"]
    [p "The fire which patiently diminishes a candle"]
    [p "Goes out; - like the hammer that falls when one sells"]
    [p "A building at an auction; -"
     [:a {:name "fn2ret"} "as"] " under a gust of wind,"] 
    [p "When a king is saved from a burning building,"]
    [p [:a {:name "fn3ret"} "A fire "] "which the heir " 
     [:a {:href "#fn2"} "who would benefit from his death"]] 
    [p "Started secretly "
     [:a {:href "#fn3"} " to see who was on his side;"]]
    [p "- As when noisily leaving a distant pistol"]
    [p "Held by a champion whose shots are always accurate,"]
    [p "A well-aimed bullet splits a lock of hair or a fly;"]
    [p "- As when a reader in bed " [:b.text-primary "((((("] "his back higher than his ears,"]
    [p "Forehead in hands, fascination keeping him awake," [:b.text-primary ")))))"]]
    [p "Devours some poignant passage"]
    [p "In which an unmarried mother " [:b.text-primary "((((("]
     "who everybody thinks is well-behaved"]
    [p "As long as her affair remains a secret" [:b.text-primary ")))))"]]
    [p [:a {:name "fn4ret"} "Who "] [:b.text-primary "((((("]
     "ready to join with hers his plenteous destiny" [:b.text-primary ")))))"]] 
    [p "Is loved by a high-level financier,"]
    [p "A young employee of whom, a year after "
     [:a {:href "#fn4"} "the sin was committed,"]]
    [p "Takes his child for a secret baptism,"]
    [p "Which will not allow him to sleep, is alas! frustrated"]
    [p [:a {:name "fn5ret"} "Because"] ", for a laugh, someone has planted in the candlestick"] 
    [p "A trick candle invisibly rigged"]
    [p [:a {:href "#fn5"} "So as not to burn any more than its tip"] ";"]
    [p "- As when he has let fly a quick sneeze"]
    [p "Followed by fervent prayers to God to bless him,"]
    [p "The man with a cold; "
     [hyperlink {:label "the sacred flame of genius"
                 :on-click #(rfe/navigate :nia.routing.canto.four/five {:id 4})}]]
    [p "Dies when its possessor grows senile"]
    [p [:b.text-primary "((((("] 
     "A flame which, however big this name or that pseudonym,"]
    [p "Is not held in the same regard by everybody;"]
    [p "- In the same way that a man has only one puppet in the bazaar"]
    [p "And its price-tag is attached;" [:b.text-primary ")))))"] " on his wall Balthazar"]
    [p "Saw written in ineradicable letters"]
    [p "Three words of living flame... then they disappeared;"]
    [p "The fire in one's eyes goes out when one reaches the age when, tooth by tooth,"]
    [p "Hair by hair, without any drastic shock, without any accident,"]
    [p "By the erosion of time, one's head empties;"]
    [:hr]
    [v-box
     :children
     [[p " Everything progresses: as at the moment when, calling the hens,"]
      [p "Those wise early-to-bedders, in to roost,"]
      [p "The sun sinks in the west, the rich man " [:b.text-danger "("] "money"]
      [p "Improves his position of privilege;"]
      [p "The elegant dunce is sure to be outstripped in a college"]
      [p "Whose crest, through pride, the elbows of the student-body"]
      [p "Have vigorously rubbed to to a shining finish;"]
      [p "To a rich suicide one gives a mass:"]
      [p "It is hard to die without a De Profundis" [:b.text-danger ")"] ";"]
      [p "Has the wicks of his old lamps re-lit,"]
      [p "A gesture which electric light has rendered out-of-date;"]
      [p "The motorcar, causing the dropping of sticks,"]
      [p "Has brought animal transport into disrepute,"]
      [p "- Since which sparrows have had a hard time;"]
      [p "And are those awkward catapults a patch on " [hyperlink {:label "cannon"}] "?"]
      [:hr]]]
    [v-box
     :children
     [[p " What things one has to wait for, alas! the moment of the "]
      [p "Splash of a pebble which one has dropped down a well,"]
      [p "Public adulations - the celebrity having died"]
      [p "Only in death acquires the right to have his statue and his street -"]
      [p "The end when in cold water a sugar-cube is dissolving,"]
      [p "For the insomniac those patches of light on the ceiling"]
      [p "Which announce dawn and its splendours,"]
      [p "In all good books the removal of the obstacle"]
      [p "Which separates the hero from perfect happiness,"]
      [p "The young wife, when her womb is not becoming heavy,"]
      [p "The lapel of a uniform for a scarlet ribbon,"]
      [p "For the thunder, when the crash comes heavily"]
      [p "Only one minute after a feeble flash of " [hyperlink {:label "lightning"}] "!"]
      [:hr]]]
    [v-box 
     :children
     [[p " Nobody is without an ambitious dream;"]
      [p "The worker sees himself dictating, during a strike,"]
      [p [:b.text-danger "("]
       "Nowadays on uses reason and everybody, eye on his goal,"]
      [p [:b.text-warning "(("]
       "We all have one; while the nape of his neck,"]
      [p "Bared to facilitate the action of the blade,"]
      [p "Is attached to his spine for another fifteen minutes,"]
      [p "Dreaming: \"He loses his prisoner - and this often happens -"]
      [p "Who holds him the tightest\", " [:b.text-info "((("] "in fact, inconsequentialities"]
      [p "Can help the long-term prisoner to break gaol,"]
      [p "Like the cheese charmed from the bill of the crow"]
      [p "- It is often best to keep silent;" [:b.text-info ")))"]]
      [p "Even the murderer has a goal: escape;" [:b.text-warning "))"]]
      [p "Whatever this ideal might be: to earn a large salary,"]
      [p "To have children, to have an abundant harvest,"]
      [p "Or to slow his heartbeat at will to achieve enlightenment,"]
      [p "Realises that in order to succeed it is better to think, to act,"]
      [p "Than to make - hard worker, barren wife,"]
      [p "Reaper or invalid - a wish at the moment when"]
      [p "A shooting-star falls across the sky;" [:b.text-danger ")"] ","]
      [p "Tired of seeing the bourgeois live off his sweat,"]
      [p [:b.text-danger "("] "Often Paul suffered and worked for Peter;"]
      [p "Vespucci exploited Columbus's efforts;"]
      [p "And it is to bedeck a finger or a chemise with pearls"]
      [p "That an oyster works so hard;" [:b.text-danger ")"] " terms to his employer;"]
      [p "The whore in her attic dreams of riding in a coach;"]
      [p "To see in his hands the amethyst and the crook"]
      [p "Is a dream dear to every young " [hyperlink {:label "priest"}] "?"]
      [:hr]]]
    [v-box 
     :children
     [[p " How the significance of words change depending upon their context!"]
      [p "Eclair means \"a flash in the sky accompanied by a bang\""]
      [p "Or \"reflection from the blade of a knife\";"]
      [p "Corbeille, when found in an epithalamium"]
      [p "Depicts the precious kingdom of the spirit,"]
      [p "Gives also \"collection of old manuscripts\"; noyau"]
      [p "Means \"comet\" here and \"cherry\" there;"]
      [p "Revolution can correspond to \"crisis"]
      [p "In which people say of an obeyed prince: \"we want him\""]
      [p "Or \"sudden shock to the nervous system\";"]
      [p "Bras shifts from \"armchair\" to \"sea\"; suite from \"chapter\" to \"king\";"]
      [p "Conduite from \"the way in which man stagnates\" to \"braid\";"]
      [p "Blanc from \"cube of chalk for grinding\" to \"civilized\";"]
      [p "Banc from \"treacherous rocks where death is in the air\" to \"uncomfortable seat\";"]
      [p "Champignon is used either for \"to eat sloppily\" or \"elegant stand\";"]
      [p "\"That which a man who is hammering must have\""]
      [p "And \"a number which oozes prestige\" are contained in clou;"]
      [p "\"He who, to clean himself up, runs a bath\""]
      [p "Is in savon, or \"that which an athlete under orders listens for\";"]
      [p "\"A sin which keeps one awake at night\""]
      [p "Or \"pigtail to tickle the neck\" in repentir;"]
      [p "\"Trait by which one habitually lies from childhood\""]
      [p "In baton or \"supreme military honour\";"]
      [p "\"Emplumed roaster of men and possessor of"]
      [p "A bow\" in naturel or \"a simple happy lack"]
      [p "Of learning; in paradis \"a smelly ball\" or \"the Heavens,"]
      [p "That beautiful flowery place sung about by pious"]
      [p "Choristers\"; \"a potted delicacy for robust"]
      [p "Gastronomes\" or \"incongruous written sorrow\" in pate;"]
      [p "\"Scientific choice of comestibles made"]
      [p "To please\" in regime or \"the way in which one is led"]
      [p "By the clique to become a conformist\";"]
      [p "\"A cry by which, the one mocking the other, an alter ego"]
      [p "Imitates you\" or \"inserted paragraph\" in echo;"]
      [p "Finally, faute depicts the slip which means that she is burdened"]
      [p "Who will never be seen by him again, or the mistake that a student"]
      [p "Geared to precision commits in his homework;"]
      [p "Well now, should one decide never to see someone again"]
      [p "Because a grammatical error has appeared in that person's " [hyperlink {:label "translation"}] "?"]
      [:hr]]]
    [v-box
     :children 
     [[p "A trick which is worth as much as these, for novelty value:"]
      [p "To induce a hen to sit on an egg"]
      [p "Which was actually laid by a duck,"]
      [p "To see the hen trembling " [:b.text-danger "("] "around whom clucking,"]
      [p "Trying to get at the duck which is foreign to the brood,"]
      [p "Menacing, beaks at the ready, is all the farmyard" [:b.text-danger ")"]]
      [p "Whilst the duckling pecks at her ankle;"]
      [p "Frightening an old lady"]
      [p [:b.text-danger "("] "A feeble one in whom the taste for celibacy"]
      [p "Was formed by fear of a drunken husband who would beat her,"]
      [p "Like the famous example of Bluebeard's widow" [:b.text-danger ")"]]
      [p "By attaching a burning rag to her cat's tail"]
      [p "And making it run in terror towards " [hyperlink {:label "her"}] "."]]]]])