(ns nia.views.cantos.one.parens-four
  (:require [re-com.core :refer [box h-box hyperlink scroller v-box]]))

(defn parens-four [{:keys [navigate]}]
  [h-box
   :align-self :center
   :style {:display :flex}
   :children
   [[box
     :style {:display :flex
             :align-items :center}
     :child [:b.text-success.display-4.m-3 "(((("]]
    [box
     :child
     [scroller
      :class "m-3"
      :height "300px"
      :child
      [:div
       [:p "Wondering thus:- if perhaps he's a thief,"]

       [:p "That fop who with"]
       [hyperlink {:on-click #(navigate :parens-five)
                   :label "one snooty glance"}]
       [:p ""]
       [:p "Enrages a poor uniformed"]
       [:p "Hotel flunkey who has just,"]
       [:p "Red-faced, brought his car to the main entrance;"]
       [:a {:name "fn1ret"} "- The new arrival in Nice"]
       [:p ", his eye on the thermometer,"]
       [:p "Whether he should wear"]
       [:a {:href "#nia1par4.fn1"} " a mackintosh"]
       [:p "to keep out the cold;"]
       [:p "Horace, alone, with what speed to make flight;"]
       [:p "- The hare sauntering through the heather"]
       [:p "If finding an old piece of gruyere is out of the question;"]
       [:p "- If the bottles of Clicquot are dancing,"]
       [:p "The diner whose nose is turning bright red;"]
       [:p "- The Yankee, if it's true that ground is more slippery"]
       [:p "Than banana peel, when climbing in the Alleghany Range;"]
       [:p "- The stranger, if there is not something of the vice-amoral"]
       [:p "In the names \"vice-president\"; or \"vice-admiral\";;"]
       [:p "- Cerberus, if he should be methodical and, before sprinkling,"]
       [:p "Sniff the street-lamp with all three nostrils;"]
       [:p "- The stroller on the pavement, cursing his luck,"]
       [:p "Whether he can get home without catching cold, his umbrella having lost its webbing;"]
       [:p "- Having become sticky and begun to pong, the sole of a shoe"]
       [:p "If its twin is jealous of its good fortune;"]
       [:p "- The farmer at dawn, putting on his smock,"]
       [:p "Which of his cockerels has begun to crow;"]
       [:p "- A conscript's shirt, when he breaks wind in the morning,"]
       [:p "What purgative he has consumed;"]
       [:p "- The baby kicking in the cot,"]
       [:p "If in being born he caused his mother's death;"]
       [:p "- The flower, if its reviving perfume, smelt"]
       [:p "Under a spreading tree, will improve a stream that stinks of asparagus;"]
       [:p "- A Jew at church, looking for a corner in the nave,"]
       [:p "Why in God's house one must keep on one's headgear;"]
       [:p "- The newspaper, which dirties its back page more,"]
       [:p "Toothpaste, pills or pawned goods;"]
       [:p "- In retrospect, Count Janot,"]
       [:p "Whether he looks old or young;"]
       [:p "- The wall, what sinful thought is his,"]
       [:p "That makes the shutter beat him in the high wind;"]
       [:p "- The bow whose hairs were slack before it was played,"]
       [:p "How much longer it must make the dud violin sound;"]
       [:p "- The thermometer placed somewhere other than the armpit"]
       [:p "If the next backside can be far away;"]
       [:p "- When wet, the knee"]
       [:p "Of the seated Papa if the nappy has been changed;"]
       [:p "- The distraught player why the ball, as if it had a mind of its own,"]
       [:p "Does not run for him when he aims at the red;"]
       [:p "- What it is that satisfies him who smells"]
       [:p "A familiar smell as he crosses the threshold of No. 100;"]
       [:p "- The bad-tempered trainer, at what winning odds"]
       [:p "Does Cocote stand in the Grand Prix;"]
       [:p "- If riding like a man will in the end"]
       [:p "Make her bow-legged, Joan of Arc;"]
       [:p "- The down-and-out, if he has found a cartwheel"]
       [:p "When maliciously he touches a hunchback's hump;"]
       [:p "- When a bag of sweets dangles from his hand,"]
       [:p "The reader, whether the mottoes will double his pleasure;"]
       [:p "- The aged astronomer if he will one day absentmindedly"]
       [:p "Confuse the Swan with a sign of the Zodiac;"]
       [:p "- Old folk, if Saint Martin's blessing can really"]
       [:p "Make it possible simultaneously to be and to have been;"]
       [:p "- The architect carrying his model, no bigger"]
       [:p "Than a toy, whether people will think he's just a kid;"]
       [:p "- The theologian, if the the Virgin owed her fame"]
       [:p "More to her son than her gossamer threads;*"]
       [:p "- The animal-trainer being eaten by a wild beast, if his widow will"]
       [:p "Dress correctly, without grey or mauve, in a year's time;"]
       [:p "- If his children will be born deaf, he whose hand"]
       [:p "Was given the day before to his first cousin;"]
       [:p "- The facetious man, if it is better to look up his cobbler's work address"]
       [:p "In the street-map or the telephone directory;*"]
       [:p "- The man waiting for his milk to heat up"]
       [:p "If he will pour it into the cup with or without its skin;"]
       [:p "- If he dares risk losing his authority by taking"]
       [:p "A purge of ellebore, the ultra-modern dramatist;"]
       [:p "- The poet, if one can with \"Auteuil\""]
       [:p "Rhyme to good effect \"comme dans un fauteuil\";"]
       [:p "- The unknown painter whether from above the stairs"]
       [:p "He will as a ghost witness the snobs arguing about his canvases;"]
       [:p "- The explorer, far from what he holds dear,"]
       [:p "Whether he'll be eaten by cannibals one day;"]
       [:p "- If her baby will be bonny, the new mother who"]
       [:span "Has yet to hold it in"
        [:a {:name "fn2ret"} "her arms"] ";"]
       [:br]
       [:span "-"
        [:a {:href "#nia1par4.fn2"} "The young author"] ","]
       [:p "for how much longer his writings will appear at his own expense;"]
       [:p "- The child, if when he puts on the ogre's big boots"]
       [:p "Tom-Thumb will whistle a wish to make them dwarf-sized;"]
       [:p "- The old man, reading an obituary,"]
       [:p "If he is himself ready for the great journey;"]
       [:p "- The President, what points he may be conceding when"]
       [:p "Signing or spitting out a speech;"]
       [:p "- The workman who knows he has swallowed a nail,"]
       [:p "If he will find it tomorrow in his turds;"]
       [:p "- The late guest risking a phoney excuse,"]
       [:p "If they will bring back the soup tureen and ladle;"]
       [:p "- What price if sold at auction, the hangman's noose"]
       [:p "Would fetch, the heir of a hanged man;"]
       [:p "- The hen, how the egg she just laid"]
       [:p "Could possibly be confused with"]
       [:a {:name "fn3ret"} "a duck's"]
       [:p ";"]
       [:p "-"]
       [:a {:href "#nia1par4.fn3"} "The ignoramus"]
       [:p "who sees a boat heading for the open sea"]
       [:p "Flying only a scrap of sail,"]
       [:p "If she is already caught in a storm;"]
       [:p "- Whose children these are, the girl whose bed,"]
       [:p "To the best of her knowledge, was never occupied;"]
       [:p "- The morphine addict, on what rank Epicurus,"]
       [:p "When classifying pleasures, would have placed injection;"]
       [:p "- The mountaineer in ecstasy on the side of a peak,"]
       [:p "How in the world enough to praise the Maker;"]
       [:p "- The bird, when (((((the sun heating even marble)))))"]
       [:p "In July one dines in the shade of a tree,"]
       [:p "Into which which plate it will, without holding back,"]
       [:p "Let drop a fresh little souvenir for examination;"]
       [:p "-  The astronomer, whether when he points a telescope at the moon"]
       [:p "He will see a man walking upside down,"]
       [:p "Like a fly slowly crawling across the celing;"] 
       [:hr]
       [:p "*Gossamer threads. A gratuitous pun: fils = \"son\" or \"gossamer"]
       [:p "threads.\""]
       [:p "*Telephone directory. Another pun: bottine = \"street-map\" and Bottin"]
       [:p "was the name of the telephone directory."]
       [:hr]
       [:a {:name "nia1par4.fn1"} "1."]
       [:p "To give an overcoat to the new arrival in Nice"]
       [:p "(Ready as he is to swear - even on days when"]
       [:p "Snowflakes big as coins float in the biting wind -"]
       [:p "That in January one can happily go naked in Nice,"]
       [:p "Just like Archimedes shouting out a hundred times \"Eureka\")"]
       [:p "Is like giving:- to the novice at sea, an emetic,"]
       [:p "When all he can hear is the wind getting up;"]
       [:p "- To a member of the audience during a speaker's preambles,"]
       [:p "A sleeping-draught; - to one in pursuit of"]
       [:p "A fast walker, a fan; - when he gets home, to a sinner"]
       [:p "Who has taken a late communion, a bitter walnut;"]
       [:p "- A false nose to a Jew, smaller than his own hooter;"]
       [:p "- Crazily, before a newly-pressed suit,"]
       [:p "An aphrodisiac to the man about to hang; - bellows"]
       [:p "To one who is furiously fighting a fire in a soot-filled"]
       [:p "Chimney; - to he who is removing from an old and cherished book"]
       [:p "A beautiful dried flower, a vice;"]
       [:p "- To he who wisely leaves a spider in peace one evening,"]
       [:p "Knowing this will bring good fortune, a lucky charm;"]
       [:p "- As with kid gloves towards the holy water"]
       [:p "She advances her trembling middle finger, to the devout lady, a charm"]
       [:p "To prevent her from wasting away; - when the express, carriage after carriage,"]
       [:p "Overtakes a slow train, to one who witnesses the contest,"]
       [:p "A prediction as to the outcome; - in the evening, to one in his hut"]
       [:p "Getting ready for bed in the dark, some hair curlers;"]
       [:p "- As, stamping, into his numb fingers"]
       [:p "A dyspeptic with bad breath blows, a ball"]
       [:p "Of stinking air to his friend;"]
       [:p "- An advantage to a steamship challenged by sail;"]
       [:p "- To a pedestrian who is being overtaken by a saddled-up horse"]
       [:p "Without rider, a double-slap on its back to make it trot;"]
       [:p "- To the worker in June who, sewing without a machine"]
       [:p "Pricks her finger, a rose to hold;"]
       [:p "As he growls before attacking, a stroke"]
       [:p "In the wrong direction down the dog's back;"]
       [:p "- When he is beset on all sides, to the foul-mouthed emaciate"]
       [:p "On the verge of ruin, a shaped block for enlarging hats;"]
       [:p "- To a recluse, when outside the flags are slapping hard,"]
       [:p "Many an undulating chromatic number on the flute;"]
       [:p "- To one overwhelmed in contemplation of a storm,"]
       [:p "The information that sound travels slower than light;"]
       [:p "- To a whistler nearing the end of a song,"]
       [:p "A slap on the back for each line of the refrain;"]
       [:p "- A rest to a cock who, autumn going by apace, stamps frustratedly"]
       [:p "As dawn is delayed; - to the Wandering Jew,"
        [:a {:href "#fn1ret"} "a desk-job"] "."]
       [:p
        [:a {:name "nia1par4.fn2"} "2."]
        [:br]
        [:a {:href "#fn2ret"} " Fame has a horror of the new."]
        [:br]]
       [:p
        [:a {:name "nia1par4.fn3"} "3."]
        [:a {:href "#fn3ret"} " Ignoramuses believe that the earth is flat."]]
       [:hr]]]]
    [box 
     :style {:display :flex
             :align-items :center}
     :child [:b.text-success.display-4 "))))"]]]])