(ns nia.views.cantos.one.parens-four
  (:require [re-com.core :refer [hyperlink v-box]]))

(defn parens-four [{:keys [navigate]}]
  [:div {:style {:display :flex
                 :flex-direction :column}}
   [v-box
    :align-self :center
    :children
    [[:div
      [:title "nia1par4"]
      [:span "((((Wondering thus:- if perhaps he's a thief,"]
      
      [:span "That fop who with"]
      [hyperlink {:on-click #(navigate :parens-five)
                  :label "one snooty glance"}]
      [:span ""]
      [:span "Enrages a poor uniformed"]
      [:span "Hotel flunkey who has just,"]
      [:span "Red-faced, brought his car to the main entrance;"]
      [:a {:name "fn1ret"} "- The new arrival in Nice"]
      [:span ", his eye on the thermometer,"]
      [:span "Whether he should wear"]
      [:a {:href "#nia1par4.fn1"} " a mackintosh"]
      [:span "to keep out the cold;"]
      [:span "Horace, alone, with what speed to make flight;"]
      [:span "- The hare sauntering through the heather"]
      [:span "If finding an old piece of gruyere is out of the question;"]
      [:span "- If the bottles of Clicquot are dancing,"]
      [:span "The diner whose nose is turning bright red;"]
      [:span "- The Yankee, if it's true that ground is more slippery"]
      [:span "Than banana peel, when climbing in the Alleghany Range;"]
      [:span "- The stranger, if there is not something of the vice-amoral"]
      [:span "In the names &quot;vice-president&quot; or &quot;vice-admiral&quot;;"]
      [:span "- Cerberus, if he should be methodical and, before sprinkling,"]
      [:span "Sniff the street-lamp with all three nostrils;"]
      [:span "- The stroller on the pavement, cursing his luck,"]
      [:span "Whether he can get home without catching cold, his umbrella having lost its webbing;"]
      [:span "- Having become sticky and begun to pong, the sole of a shoe"]
      [:span "If its twin is jealous of its good fortune;"]
      [:span "- The farmer at dawn, putting on his smock,"]
      [:span "Which of his cockerels has begun to crow;"]
      [:span "- A conscript's shirt, when he breaks wind in the morning,"]
      [:span "What purgative he has consumed;"]
      [:span "- The baby kicking in the cot,"]
      [:span "If in being born he caused his mother's death;"]
      [:span "- The flower, if its reviving perfume, smelt"]
      [:span "Under a spreading tree, will improve a stream that stinks of asparagus;"]
      [:span "- A Jew at church, looking for a corner in the nave,"]
      [:span "Why in God's house one must keep on one's headgear;"]
      [:span "- The newspaper, which dirties its back page more,"]
      [:span "Toothpaste, pills or pawned goods;"]
      [:span "- In retrospect, Count Janot,"]
      [:span "Whether he looks old or young;"]
      [:span "- The wall, what sinful thought is his,"]
      [:span "That makes the shutter beat him in the high wind;"]
      [:span "- The bow whose hairs were slack before it was played,"]
      [:span "How much longer it must make the dud violin sound;"]
      [:span "- The thermometer placed somewhere other than the armpit"]
      [:span "If the next backside can be far away;"]
      [:span "- When wet, the knee"]
      [:span "Of the seated Papa if the nappy has been changed;"]
      [:span "- The distraught player why the ball, as if it had a mind of its own,"]
      [:span "Does not run for him when he aims at the red;"]
      [:span "- What it is that satisfies him who smells"]
      [:span "A familiar smell as he crosses the threshold of No. 100;"]
      [:span "- The bad-tempered trainer, at what winning odds"]
      [:span "Does Cocote stand in the Grand Prix;"]
      [:span "- If riding like a man will in the end"]
      [:span "Make her bow-legged, Joan of Arc;"]
      [:span "- The down-and-out, if he has found a cartwheel"]
      [:span "When maliciously he touches a hunchback's hump;"]
      [:span "- When a bag of sweets dangles from his hand,"]
      [:span "The reader, whether the mottoes will double his pleasure;"]
      [:span "- The aged astronomer if he will one day absentmindedly"]
      [:span "Confuse the Swan with a sign of the Zodiac;"]
      [:span "- Old folk, if Saint Martin's blessing can really"]
      [:span "Make it possible simultaneously to be and to have been;"]
      [:span "- The architect carrying his model, no bigger"]
      [:span "Than a toy, whether people will think he's just a kid;"]
      [:span "- The theologian, if the the Virgin owed her fame"]
      [:span "More to her son than her gossamer threads;*"]
      [:span "- The animal-trainer being eaten by a wild beast, if his widow will"]
      [:span "Dress correctly, without grey or mauve, in a year's time;"]
      [:span "- If his children will be born deaf, he whose hand"]
      [:span "Was given the day before to his first cousin;"]
      [:span "- The facetious man, if it is better to look up his cobbler's work address"]
      [:span "In the street-map or the telephone directory;*"]
      [:span "- The man waiting for his milk to heat up"]
      [:span "If he will pour it into the cup with or without its skin;"]
      [:span "- If he dares risk losing his authority by taking"]
      [:span "A purge of ellebore, the ultra-modern dramatist;"]
      [:span "- The poet, if one can with &quot;Auteuil&quot;"]
      [:span "Rhyme to good effect &quot;comme dans un fauteuil&quot;;"]
      [:span "- The unknown painter whether from above the stairs"]
      [:span "He will as a ghost witness the snobs arguing about his canvases;"]
      [:span "- The explorer, far from what he holds dear,"]
      [:span "Whether he'll be eaten by cannibals one day;"]
      [:span "- If her baby will be bonny, the new mother who"]
      [:span "Has yet to hold it in"]
      [:a {:name "fn2ret"} "her arms"]
      [:span ";"]
      [:span "-"]
      [:a {:href "#nia1par4.fn2"} "The young author"]
      [:span ","]
      [:span "for how much longer his writings will appear at his own expense;"]
      [:span "- The child, if when he puts on the ogre's big boots"]
      [:span "Tom-Thumb will whistle a wish to make them dwarf-sized;"]
      [:span "- The old man, reading an obituary,"]
      [:span "If he is himself ready for the great journey;"]
      [:span "- The President, what points he may be conceding when"]
      [:span "Signing or spitting out a speech;"]
      [:span "- The workman who knows he has swallowed a nail,"]
      [:span "If he will find it tomorrow in his turds;"]
      [:span "- The late guest risking a phoney excuse,"]
      [:span "If they will bring back the soup tureen and ladle;"]
      [:span "- What price if sold at auction, the hangman's noose"]
      [:span "Would fetch, the heir of a hanged man;"]
      [:span "- The hen, how the egg she just laid"]
      [:span "Could possibly be confused with"]
      [:a {:name "fn3ret"} "a duck's"]
      [:span ";"]
      [:span "-"]
      [:a {:href "#nia1par4.fn3"} "The ignoramus"]
      [:span "who sees a boat heading for the open sea"]
      [:span "Flying only a scrap of sail,"]
      [:span "If she is already caught in a storm;"]
      [:span "- Whose children these are, the girl whose bed,"]
      [:span "To the best of her knowledge, was never occupied;"]
      [:span "- The morphine addict, on what rank Epicurus,"]
      [:span "When classifying pleasures, would have placed injection;"]
      [:span "- The mountaineer in ecstasy on the side of a peak,"]
      [:span "How in the world enough to praise the Maker;"]
      [:span "- The bird, when (((((the sun heating even marble)))))"]
      [:span "In July one dines in the shade of a tree,"]
      [:span "Into which which plate it will, without holding back,"]
      [:span "Let drop a fresh little souvenir for examination;"]
      [:span "-  The astronomer, whether when he points a telescope at the moon"]
      [:span "He will see a man walking upside down,"]
      [:span "Like a fly slowly crawling across the celing;))))"]
      [:hr]
      [:span "*Gossamer threads. A gratuitous pun: fils = &quot;son&quot; or &quot;gossamer"]
      [:span "threads.&quot;"]
      [:span "*Telephone directory. Another pun: bottine = &quot;street-map&quot; and Bottin"]
      [:span "was the name of the telephone directory."]
      [:p "\n\n"]
      [:hr]
      [:span "Click"]
      [:a {:href "nia1thesis.html"} "here"]
      [:span "to return to thesis"]
      [:span "Click"]
      [:a {:href "nia1par1.html"} " here"]
      [:span "to return to parenthesis 1"]
      [:span "Click"]
      [:a {:href "nia1par2.html"} "here"]
      [:span "to return to parenthesis 2"]
      [:span "Click"]
      [:a {:href "nia1par3.html"} "here"]
      [:span "to return to parenthesis 3"]
      [:hr]
      [:span ""]
      [:a {:name "nia1par4.fn1"} "1."]
      [:span ""]
      [:span "To give an overcoat to the new arrival in Nice"]
      [:span "(Ready as he is to swear - even on days when"]
      [:span "Snowflakes big as coins float in the biting wind -"]
      [:span "That in January one can happily go naked in Nice,"]
      [:span "Just like Archimedes shouting out a hundred times &quot;Eureka&quot;)"]
      [:span "Is like giving:- to the novice at sea, an emetic,"]
      [:span "When all he can hear is the wind getting up;"]
      [:span "- To a member of the audience during a speaker's preambles,"]
      [:span "A sleeping-draught; - to one in pursuit of"]
      [:span "A fast walker, a fan; - when he gets home, to a sinner"]
      [:span "Who has taken a late communion, a bitter walnut;"]
      [:span "- A false nose to a Jew, smaller than his own hooter;"]
      [:span "- Crazily, before a newly-pressed suit,"]
      [:span "An aphrodisiac to the man about to hang; - bellows"]
      [:span "To one who is furiously fighting a fire in a soot-filled"]
      [:span "Chimney; - to he who is removing from an old and cherished book"]
      [:span "A beautiful dried flower, a vice;"]
      [:span "- To he who wisely leaves a spider in peace one evening,"]
      [:span "Knowing this will bring good fortune, a lucky charm;"]
      [:span "- As with kid gloves towards the holy water"]
      [:span "She advances her trembling middle finger, to the devout lady, a charm"]
      [:span "To prevent her from wasting away; - when the express, carriage after carriage,"]
      [:span "Overtakes a slow train, to one who witnesses the contest,"]
      [:span "A prediction as to the outcome; - in the evening, to one in his hut"]
      [:span "Getting ready for bed in the dark, some hair curlers;"]
      [:span "- As, stamping, into his numb fingers"]
      [:span "A dyspeptic with bad breath blows, a ball"]
      [:span "Of stinking air to his friend;"]
      [:span "- An advantage to a steamship challenged by sail;"]
      [:span "- To a pedestrian who is being overtaken by a saddled-up horse"]
      [:span "Without rider, a double-slap on its back to make it trot;"]
      [:span "- To the worker in June who, sewing without a machine"]
      [:span "Pricks her finger, a rose to hold;"]
      [:span "As he growls before attacking, a stroke"]
      [:span "In the wrong direction down the dog's back;"]
      [:span "- When he is beset on all sides, to the foul-mouthed emaciate"]
      [:span "On the verge of ruin, a shaped block for enlarging hats;"]
      [:span "- To a recluse, when outside the flags are slapping hard,"]
      [:span "Many an undulating chromatic number on the flute;"]
      [:span "- To one overwhelmed in contemplation of a storm,"]
      [:span "The information that sound travels slower than light;"]
      [:span "- To a whistler nearing the end of a song,"]
      [:span "A slap on the back for each line of the refrain;"]
      [:span "- A rest to a cock who, autumn going by apace, stamps frustratedly"]
      [:span "As dawn is delayed; - to the Wandering Jew,"]
      [:a {:href "#fn1ret"} "a desk-job"]
      [:span "."]
      [:p 
       [:a {:name "nia1par4.fn2"} "2."] 
       [:br] 
       [:a {:href "#fn2ret"} " Fame has a horror of the new."]
       [:br]]
      [:p 
       [:a {:name "nia1par4.fn3"} "3."] 
       [:a {:href "#fn3ret"} " Ignoramuses believe that the earth is flat."]] 
      [:hr]
      [:span "Click"]
      [:a {:href "nia1thesis.html"} "here"]
      [:span "to return to thesis"]
      [:span "Click"]
      [:a {:href "nia1par1.html"} " here"]
      [:span "to return to parenthesis 1"]
      [:span "Click"]
      [:a {:href "nia1par2.html"} "here"]
      [:span "to return to parenthesis 2"]
      [:span "Click"]
      [:a {:href "nia1par3.html"} "here"]
      [:span "to return to parenthesis 3"]
      [:hr]]]]])