
import "./base.js";
import "./cljs-runtime/shadow.module.storage.prepend.js";
SHADOW_ENV.setLoaded("shadow.module.storage.prepend.js");
import "./cljs-runtime/ajax.protocols.js";
SHADOW_ENV.setLoaded("ajax.protocols.js");
import "./cljs-runtime/ajax.util.js";
SHADOW_ENV.setLoaded("ajax.util.js");
import "./cljs-runtime/ajax.url.js";
SHADOW_ENV.setLoaded("ajax.url.js");
import "./cljs-runtime/ajax.interceptors.js";
SHADOW_ENV.setLoaded("ajax.interceptors.js");
import "./cljs-runtime/ajax.json.js";
SHADOW_ENV.setLoaded("ajax.json.js");
import "./cljs-runtime/ajax.transit.js";
SHADOW_ENV.setLoaded("ajax.transit.js");
import "./cljs-runtime/ajax.formats.js";
SHADOW_ENV.setLoaded("ajax.formats.js");
import "./cljs-runtime/ajax.ring.js";
SHADOW_ENV.setLoaded("ajax.ring.js");
import "./cljs-runtime/goog.json.hybrid.js";
SHADOW_ENV.setLoaded("goog.json.hybrid.js");
import "./cljs-runtime/goog.log.log.js";
SHADOW_ENV.setLoaded("goog.log.log.js");
import "./cljs-runtime/goog.net.errorcode.js";
SHADOW_ENV.setLoaded("goog.net.errorcode.js");
import "./cljs-runtime/goog.net.eventtype.js";
SHADOW_ENV.setLoaded("goog.net.eventtype.js");
import "./cljs-runtime/goog.net.httpstatus.js";
SHADOW_ENV.setLoaded("goog.net.httpstatus.js");
import "./cljs-runtime/goog.net.xhrlike.js";
SHADOW_ENV.setLoaded("goog.net.xhrlike.js");
import "./cljs-runtime/goog.net.xmlhttpfactory.js";
SHADOW_ENV.setLoaded("goog.net.xmlhttpfactory.js");
import "./cljs-runtime/goog.net.wrapperxmlhttpfactory.js";
SHADOW_ENV.setLoaded("goog.net.wrapperxmlhttpfactory.js");
import "./cljs-runtime/goog.net.xmlhttp.js";
SHADOW_ENV.setLoaded("goog.net.xmlhttp.js");
import "./cljs-runtime/goog.net.xhrio.js";
SHADOW_ENV.setLoaded("goog.net.xhrio.js");
import "./cljs-runtime/ajax.simple.js";
SHADOW_ENV.setLoaded("ajax.simple.js");
import "./cljs-runtime/ajax.easy.js";
SHADOW_ENV.setLoaded("ajax.easy.js");
import "./cljs-runtime/goog.structs.queue.js";
SHADOW_ENV.setLoaded("goog.structs.queue.js");
import "./cljs-runtime/goog.structs.collection.js";
SHADOW_ENV.setLoaded("goog.structs.collection.js");
import "./cljs-runtime/goog.structs.set.js";
SHADOW_ENV.setLoaded("goog.structs.set.js");
import "./cljs-runtime/goog.structs.pool.js";
SHADOW_ENV.setLoaded("goog.structs.pool.js");
import "./cljs-runtime/goog.structs.node.js";
SHADOW_ENV.setLoaded("goog.structs.node.js");
import "./cljs-runtime/goog.structs.heap.js";
SHADOW_ENV.setLoaded("goog.structs.heap.js");
import "./cljs-runtime/goog.structs.priorityqueue.js";
SHADOW_ENV.setLoaded("goog.structs.priorityqueue.js");
import "./cljs-runtime/goog.structs.prioritypool.js";
SHADOW_ENV.setLoaded("goog.structs.prioritypool.js");
import "./cljs-runtime/goog.net.xhriopool.js";
SHADOW_ENV.setLoaded("goog.net.xhriopool.js");
import "./cljs-runtime/goog.net.xhrmanager.js";
SHADOW_ENV.setLoaded("goog.net.xhrmanager.js");
import "./cljs-runtime/ajax.xhrio.js";
SHADOW_ENV.setLoaded("ajax.xhrio.js");
import "./cljs-runtime/ajax.xml_http_request.js";
SHADOW_ENV.setLoaded("ajax.xml_http_request.js");
import "./cljs-runtime/ajax.core.js";
SHADOW_ENV.setLoaded("ajax.core.js");
import "./cljs-runtime/nia.config.storage.js";
SHADOW_ENV.setLoaded("nia.config.storage.js");
import "./cljs-runtime/nia.events.storage.js";
SHADOW_ENV.setLoaded("nia.events.storage.js");
import "./cljs-runtime/shadow.module.storage.append.js";
SHADOW_ENV.setLoaded("shadow.module.storage.append.js");


shadow.cljs.devtools.client.env.module_loaded("storage");